services:
  frontend:
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    environment:
      BACKEND_URL: "http://rembackend:3050"
    networks:
      - backend_default

networks:
  backend_default:
    external: true
      
