services:
  rembackend:
    container_name: rembackend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres_database
    volumes:
      - ./dev-creds:/vault/secrets/dev-creds
    networks:
      - rem-net
    ports:
      - "127.0.0.1:3050:3050"
    depends_on:
      - postgres_database
        #- redis-cache

  postgres_database:
    container_name: postgres_database
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      #- postgres:/var/lib/postgresql/data
      - ./backend/drizzle:/drizzle
      - ./scripts/execute_sql_migration.sh:/execute_sql_migration.sh
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - rem-net
    restart: unless-stopped

      #  redis-cache:
      #    container_name: redis-cache
      #    image: redis:7.2.3-alpine
      #    restart: always
      #    ports:
      #      - "6379:6379"
      #    command: redis-server --save 20 1 --loglevel warning --requirepass devpw
      #    volumes:
      #      - cache:/data

networks:
  rem-net:

volumes:
  postgres:
  cache:
