services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres_database
      FRONTEND_HOST: "127.0.0.1"  
    volumes:
      - ./dev-creds:/vault/secrets/dev-creds
    ports:
      - "127.0.0.1:3050:3050"
    depends_on:
      - postgres_database

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        APP_ENV: development 
        FRONTEND_HOST: "frontend"  
        NEXT_PUBLIC_APP_ENV: development  
        NEXT_PUBLIC_BACKEND_HOST: "127.0.0.1"
        NEXT_PUBLIC_BACKEND_PORT: 3050
        DOCKER_BACKEND_HOST: host.docker.internal
    env_file:
      - .env
    environment:
      FRONTEND_HOST: frontend
      DOCKER_BACKEND_HOST: host.docker.internal
    ports:
      - "127.0.0.1:3000:3000"

  postgres_database:
    container_name: postgres_database
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      #- postgres:/var/lib/postgresql/data
      - ./backend/drizzle:/drizzle
      - ./scripts/execute_sql_migration.sh:/execute_sql_migration.sh
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

      #  redis-cache:
      #    container_name: redis-cache
      #    image: redis:7.2.3-alpine
      #    restart: always
      #    ports:
      #      - "6379:6379"
      #    command: redis-server --save 20 1 --loglevel warning --requirepass devpw
      #    volumes:
      #      - cache:/data

networks:
  rem-net:

volumes:
  postgres:
  cache:
