name: Deployment Backend

on:
  release:
    types:
      - prereleased

defaults:
  run:
    working-directory: backend

jobs:
  build-image:
    runs-on: ubuntu-22.04
    name: build & push docker image
    #if: github.ref == 'refs/heads/master'
    env:
      IMG_NAME: ${{ vars.BACKEND_IMAGE }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout backend
        with:
          sparse-checkout: |
            ./backend
      - name: debug
        run: |
          echo "backend image name -> $IMG_NAME"
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with: 
          image: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{raw}}
      - name: log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
