name: Rememberry Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/integration-frontend.yml"
    branches: [master]

jobs:
  lint-format:
    name: lint and format
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: get pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: lint
        run: pnpm run frontend lint
      - name: check formatting
        run: |
          if ! pnpm run format-check; then
            echo "Please format the code by running: pnpm run format"
            exit 1
          fi

  test:
    name: test frontend
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: get pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: test
        run: pnpm run frontend test

  build:
    name: build
    runs-on: ubuntu-22.04
    env:
      NEXT_PUBLIC_BACKEND_HOST: "localhost"
      NEXT_PUBLIC_BACKEND_PORT: "3050"
      NEXT_PUBLIC_APP_ENV: "development"
      APP_ENV: "development"
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: get pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: use node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: install dependencies
        run: pnpm i --frozen-lockfile
      - name: build
        run: pnpm run frontend build
