name: Rememberry Backend CI

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/integration-backend.yml"
    branches: [master]

defaults:
  run:
    working-directory: backend

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout backend
        with:
          sparse-checkout: |
            ./backend
      - uses: oven-sh/setup-bun@v1
        name: Get bun
        with:
          bun-version: 1.0.6
      - run: bun install --frozen-lockfile
        name: Install dependecies
      - run: bun run test
        name: test with bun

  lint-format: 
    name: lint and format backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout backend
        with:
          sparse-checkout: |
            ./backend
      - uses: oven-sh/setup-bun@v1
        name: Get bun
        with:
          bun-version: 1.0.6
      - run: bun install --frozen-lockfile
        name: Install dependecies
      - run: |
          if ! bunx prettier --check .; then
            echo "Please format the code by running: bun run format"
            exit 1
          fi
        name: Check code formatting

  test-build:
    name: build to check compilation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout backend
        with:
          sparse-checkout: |
            ./backend
      - uses: oven-sh/setup-bun@v1
        name: Get bun
        with:
          bun-version: 1.0.6
      - run: bun install --frozen-lockfile
        name: Install dependecies
      - run: bun run build
        name: build the project with bun

