name: Database Migration

on:
  push:
    paths:
    - 'drizzle/**'
    branches:
    - master 

jobs:
  run-migrations:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: | 
          ./backend/drizzle
          ./backend/scripts/kube-execute-sql.sh
          ./backend/scripts/run-kube-migration.sh
    - uses: azure/setup-kubectl@v3
      with:
        version: 1.28
      id: install
    - name: Run migrations
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      run: |
        echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config

        sudo chmod +x run-kube-migration.sh
        ./run-kube-migration

