name: Staging Database Migration

on: workflow_dispatch

  #  #on:
  #  #  push:
  #  #    paths:
  #  #    - './backend/drizzle/**'
  #  #    branches:
  #  #    - master 

jobs:
  run-migrations:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      name: checkout deployments
      with:
        submodules: "recursive"
    - name: set the kubernetes context
      uses: azure/k8s-set-context@v3
      with:
        method: service-account
        k8s-url: ${{ secrets.KUBE_SERVER_URL }}
        k8s-secret: ${{ secrets.KUBE_SERVICE_ACC_SECRET }}
    - name: Run migrations
      run: |
        set +e
        
        cleanup() {
            echo "Cleaning up..."
            kubectl delete -f /home/runner/work/rememberry/rememberry/deployments/database-migration/staging-migration.yaml
            kubectl delete configmap -n rememberry migration
            kubectl delete configmap -n rememberry drizzle
            echo "Cleanup finished."
        }
        
        trap cleanup EXIT
        
        kubectl create configmap -n rememberry migration --from-file=/home/runner/work/rememberry/rememberry/deployments/database-migration/apply-migration.sh
        kubectl create configmap -n rememberry drizzle --from-file=/home/runner/work/rememberry/rememberry/backend/drizzle
        
        kubectl apply -f /home/runner/work/rememberry/rememberry/deployments/database-migration/staging-migration.yaml
        
        echo "Waiting for 30 seconds..."
        sleep 30
        echo "Resuming operations..."

