name: Staging Deployment Frontend 

on:
  push:
    tags:
      - 'frontend-v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]*'

jobs:
  build-image:
    runs-on: ubuntu-22.04
    name: build & push docker image
      # if: github.ref == 'refs/heads/master'
    # Current Solution is to directly pass in the pararmeter for the host and port 
    # so there is no build time error should be fixed at some time
    steps:
      - uses: actions/checkout@v4
        name: checkout frontend and backend
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare tag
        id: prepare
        shell: bash
        run: |
          echo "tag=${GITHUB_REF#refs/tags/frontend-}" >> $GITHUB_ENV
      - name: docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with: 
          images: notemann27/rememberry-frontend
          tags: |
            type=raw,value=${{ env.tag }}
      - name: log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: |
            "NEXT_PUBLIC_BACKEND_HOST=api.stage.rememberry.app"
            "NEXT_PUBLIC_APP_ENV=staging"
            "NEXT_PUBLIC_BACKEND_PORT=3050"
            "APP_ENV=staging"



  staging:
    runs-on: ubuntu-22.04
    name: deploy changes on staging
      # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        name: checkout frontend and backend
