name: Staging Database Migration

on: workflow_dispatch

  #  #on:
  #  #  push:
  #  #    paths:
  #  #    - './backend/drizzle/**'
  #  #    branches:
  #  #    - master 

jobs:
  run-migrations:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      name: checkout deployments
      with:
        submodules: "recursive"
    - uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0
      id: install
    - name: Run migrations
      env:
        KUBE_SERVICE_ACC: ${{ secrets.KUBE_SERVICE_ACC }}
        KUBE_SERVICE_ACC_CA_CERT: ${{ secrets.KUBE_SERVICE_ACC_CA_CERT }}
        KUBE_SERVER_URL: ${{ secrets.KUBE_SERVER_URL }}
      run: |
        echo "$KUBE_SERVICE_ACC_CA_CERT" > /home/runner/work/rememberry/rememberry/.ca.cert
        
        kubectl config set-cluster hetzner --server=$KUBE_SERVER_URL --certificate-authority=/home/runner/work/rememberry/rememberry/.ca.cert --embed-certs=true
        kubectl config set-credentials gha-user --token=$KUBE_SERVICE_ACC
        kubectl config set-context hetzner-gha --cluster=hetzner --user=gha-user --namespace=rememberry
        kubectl config use-context hetzner-gha

        kubectl create configmap -n rememberry migration --from-file=/home/runner/work/rememberry/rememberry/deployments/database-migration/apply-migration.sh

        kubectl create configmap -n rememberry migration --from-file=/home/runner/work/rememberry/rememberry/backend/drizzle

        kubectl apply -f /home/runner/work/rememberry/rememberry/deployments/database-migration/staging-migration.yaml

        sleep 10

        kubectl delete -f /home/runner/work/rememberry/rememberry/deployments/database-migration/staging-migration.yaml
