name: Staging Deployment Backend 

on:
  push:
    tags:
      - 'backend-v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]*'

defaults:
  run:
    working-directory: backend

jobs:
  build-image:
    runs-on: ubuntu-22.04
    name: build & push docker image
      # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        name: checkout backend
        with:
          sparse-checkout: |
            ./backend
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare tag
        id: prepare
        shell: bash
        run: |
          echo "tag=${GITHUB_REF#refs/tags/backend-}" >> $GITHUB_ENV
      - name: docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with: 
          images: notemann27/rememberry-backend
          tags: |
            type=raw,value=${{ env.tag }}
      - name: log in to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

  staging:
    runs-on: ubuntu-22.04
    name: deploy changes on staging
      # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        name: checkout backend
        with:
          sparse-checkout: |
            ./backend
